//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KPMG_Assignment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Constants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Constants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KPMG_Assignment.Constants", typeof(Constants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GetUploadedData.
        /// </summary>
        internal static string ACTION_NAME_GET_UPLOADED_DATA {
            get {
                return ResourceManager.GetString("ACTION_NAME_GET_UPLOADED_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowAccounts.
        /// </summary>
        internal static string ACTION_NAME_SHOW_ACCOUNTS {
            get {
                return ResourceManager.GetString("ACTION_NAME_SHOW_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string COLUMN_NAME_ACCOUNT {
            get {
                return ResourceManager.GetString("COLUMN_NAME_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string COLUMN_NAME_AMOUNT {
            get {
                return ResourceManager.GetString("COLUMN_NAME_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrencyCode.
        /// </summary>
        internal static string COLUMN_NAME_CURRENCY_CODE {
            get {
                return ResourceManager.GetString("COLUMN_NAME_CURRENCY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string COLUMN_NAME_DESCRIPTION {
            get {
                return ResourceManager.GetString("COLUMN_NAME_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason.
        /// </summary>
        internal static string COLUMN_NAME_REASON {
            get {
                return ResourceManager.GetString("COLUMN_NAME_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to kpmgConnection.
        /// </summary>
        internal static string CONNECTION_STRING {
            get {
                return ResourceManager.GetString("CONNECTION_STRING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TABLE_NAME.
        /// </summary>
        internal static string TABLE_NAME {
            get {
                return ResourceManager.GetString("TABLE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPMG_Accounts.
        /// </summary>
        internal static string TABLE_NAME_ACCOUNTS {
            get {
                return ResourceManager.GetString("TABLE_NAME_ACCOUNTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KPMG_Invalid_Accounts.
        /// </summary>
        internal static string TABLE_NAME_INVALID_ACCTS {
            get {
                return ResourceManager.GetString("TABLE_NAME_INVALID_ACCTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload a file of type:.
        /// </summary>
        internal static string USE_MESSAGE_UPLOAD_FILE_TYPE {
            get {
                return ResourceManager.GetString("USE_MESSAGE_UPLOAD_FILE_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your file is too large, maximum allowed size is :.
        /// </summary>
        internal static string USER_MESSAGE_FILE_BIG {
            get {
                return ResourceManager.GetString("USER_MESSAGE_FILE_BIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Account info.
        /// </summary>
        internal static string VAL_MSG_NO_ACCOUNT {
            get {
                return ResourceManager.GetString("VAL_MSG_NO_ACCOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to | No Amount.
        /// </summary>
        internal static string VAL_MSG_NO_AMOUNT {
            get {
                return ResourceManager.GetString("VAL_MSG_NO_AMOUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | Invalid currency code.
        /// </summary>
        internal static string VAL_MSG_NO_CURRENCY_CODE {
            get {
                return ResourceManager.GetString("VAL_MSG_NO_CURRENCY_CODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  | No Account description.
        /// </summary>
        internal static string VAL_MSG_NO_DESC {
            get {
                return ResourceManager.GetString("VAL_MSG_NO_DESC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;Extended Properties=&quot;Excel 8.0;HDR=Yes;IMEX=2&quot;.
        /// </summary>
        internal static string XLS_EXTENDED_PROPERTIES {
            get {
                return ResourceManager.GetString("XLS_EXTENDED_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xls.
        /// </summary>
        internal static string XLS_FILE_EXTENTION {
            get {
                return ResourceManager.GetString("XLS_FILE_EXTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.Jet.OLEDB.4.0;Data Source=.
        /// </summary>
        internal static string XLS_PROVIDER {
            get {
                return ResourceManager.GetString("XLS_PROVIDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ;Extended Properties=&quot;Excel 12.0;HDR=Yes;IMEX=2&quot;.
        /// </summary>
        internal static string XLSX_EXTENDED_PROPERTIES {
            get {
                return ResourceManager.GetString("XLSX_EXTENDED_PROPERTIES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .xlsx.
        /// </summary>
        internal static string XLSX_FILE_EXTENTION {
            get {
                return ResourceManager.GetString("XLSX_FILE_EXTENTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider=Microsoft.ACE.OLEDB.12.0;Data Source=.
        /// </summary>
        internal static string XLSX_PROVIDER {
            get {
                return ResourceManager.GetString("XLSX_PROVIDER", resourceCulture);
            }
        }
    }
}
